version: '3.7'
services:
  postgrsql_db:
    image: postgres:14
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql  # Updated path
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=user_management_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
